tropomi_filepath: PATH
clon: -101.750008
clat: 31.491669
xres: 0.0083333
yres: 0.0083333

tropomi_train_file: PATH
tropomi_test_file: PATH
lat_lon_file: PATH
tropomi_bkg_file: PATH

ems_buffer_days: 7
upwind_degree_margin: 1
upwind_date_margin: 4
buffer_months: 6
obs_indices_margin: 100
met_temp_resolution_background: 6 # hours wind data for computing background 

HRRR_DIR: PATH
HRRR_LAT_LON_MAPPING: PATH
trimsize: 150

model_path: PATH
footprint_path: PATH
maximum_domain_trajectory: 424.264

inventory_type: "EPA"
inventory_path: PATH
ems_scaling_factor: 4
ems_uncert: 0.5

output_path: PATH
